routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('users', 'UserController');

Route::resource('userGroups', 'UserGroupController');

Route::resource('groupMembers', 'GroupMemberController');

Route::resource('avatars', 'AvatarController');

Route::resource('statusTemplateInspections', 'StatusTemplateInspectionController');

Route::resource('templateInspections', 'TemplateInspectionController');

Route::resource('statusInspectionForms', 'StatusInspectionFormController');

Route::resource('inspectionForms', 'InspectionFormController');

Route::resource('inspectionResponses', 'InspectionResponseController');

Route::resource('categoryInspectionForms', 'CategoryInspectionFormController');

Route::resource('statusCategoryForms', 'StatusCategoryFormController');

Route::resource('typeFormItems', 'TypeFormItemController');

Route::resource('inspectionFormItems', 'InspectionFormItemController');

Route::resource('priorityActionPlans', 'PriorityActionPlanController');

Route::resource('actionPlans', 'ActionPlanController');

Route::resource('observationFormItems', 'ObservationFormItemController');

Route::resource('optionFormItems', 'OptionFormItemController');

Route::resource('photographicEvidences', 'PhotographicEvidenceController');

Route::resource('typeRecurrences', 'TypeRecurrenceController');

Route::resource('customDateScheduleds', 'CustomDateScheduledController');

Route::resource('recurrenceScheduleds', 'RecurrenceScheduledController');

app/Models/OptionFormItem.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class OptionFormItem
 * @package App\Models
 * @version August 3, 2018, 12:37 pm -05
 *
 * @property string form_code_item
 * @property string label
 * @property string value
 */
class OptionFormItem extends Model
{

    public $table = 'options_form_items';
    


    public $fillable = [
        'form_code_item',
        'label',
        'value'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'form_code_item' => 'string',
        'label' => 'string',
        'value' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'form_code_item' => 'required,string',
        'label' => 'required',
        'value' => 'required'
    ];

    
}

app/Http/Controllers/OptionFormItemController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\OptionFormItemDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateOptionFormItemRequest;
use App\Http\Requests\UpdateOptionFormItemRequest;
use App\Repositories\OptionFormItemRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class OptionFormItemController extends AppBaseController
{
    /** @var  OptionFormItemRepository */
    private $optionFormItemRepository;

    public function __construct(OptionFormItemRepository $optionFormItemRepo)
    {
        $this->optionFormItemRepository = $optionFormItemRepo;
    }

    /**
     * Display a listing of the OptionFormItem.
     *
     * @param OptionFormItemDataTable $optionFormItemDataTable
     * @return Response
     */
    public function index(OptionFormItemDataTable $optionFormItemDataTable)
    {
        return $optionFormItemDataTable->render('option_form_items.index');
    }

    /**
     * Show the form for creating a new OptionFormItem.
     *
     * @return Response
     */
    public function create()
    {
        return view('option_form_items.create');
    }

    /**
     * Store a newly created OptionFormItem in storage.
     *
     * @param CreateOptionFormItemRequest $request
     *
     * @return Response
     */
    public function store(CreateOptionFormItemRequest $request)
    {
        $input = $request->all();

        $optionFormItem = $this->optionFormItemRepository->create($input);

        Flash::success('Option Form Item saved successfully.');

        return redirect(route('optionFormItems.index'));
    }

    /**
     * Display the specified OptionFormItem.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $optionFormItem = $this->optionFormItemRepository->findWithoutFail($id);

        if (empty($optionFormItem)) {
            Flash::error('Option Form Item not found');

            return redirect(route('optionFormItems.index'));
        }

        return view('option_form_items.show')->with('optionFormItem', $optionFormItem);
    }

    /**
     * Show the form for editing the specified OptionFormItem.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $optionFormItem = $this->optionFormItemRepository->findWithoutFail($id);

        if (empty($optionFormItem)) {
            Flash::error('Option Form Item not found');

            return redirect(route('optionFormItems.index'));
        }

        return view('option_form_items.edit')->with('optionFormItem', $optionFormItem);
    }

    /**
     * Update the specified OptionFormItem in storage.
     *
     * @param  int              $id
     * @param UpdateOptionFormItemRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOptionFormItemRequest $request)
    {
        $optionFormItem = $this->optionFormItemRepository->findWithoutFail($id);

        if (empty($optionFormItem)) {
            Flash::error('Option Form Item not found');

            return redirect(route('optionFormItems.index'));
        }

        $optionFormItem = $this->optionFormItemRepository->update($request->all(), $id);

        Flash::success('Option Form Item updated successfully.');

        return redirect(route('optionFormItems.index'));
    }

    /**
     * Remove the specified OptionFormItem from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $optionFormItem = $this->optionFormItemRepository->findWithoutFail($id);

        if (empty($optionFormItem)) {
            Flash::error('Option Form Item not found');

            return redirect(route('optionFormItems.index'));
        }

        $this->optionFormItemRepository->delete($id);

        Flash::success('Option Form Item deleted successfully.');

        return redirect(route('optionFormItems.index'));
    }
}

resources/views/option_form_items/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Option Form Item
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'optionFormItems.store']) !!}

                        @include('option_form_items.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/option_form_items/datatables_actions.blade.php
{!! Form::open(['route' => ['optionFormItems.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('optionFormItems.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('optionFormItems.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/option_form_items/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Option Form Item
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($optionFormItem, ['route' => ['optionFormItems.update', $optionFormItem->id], 'method' => 'patch']) !!}

                        @include('option_form_items.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/option_form_items/fields.blade.php
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('optionFormItems.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/option_form_items/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Option Form Items</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('optionFormItems.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('option_form_items.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $optionFormItems])

        </div>
    </div>
@endsection

resources/views/option_form_items/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Option Form Item
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('option_form_items.show_fields')
                    <a href="{!! route('optionFormItems.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/option_form_items/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $optionFormItem->id !!}</p>
</div>

<!-- Form Code Item Field -->
<div class="form-group">
    {!! Form::label('form_code_item', 'Form Code Item:') !!}
    <p>{!! $optionFormItem->form_code_item !!}</p>
</div>

<!-- Label Field -->
<div class="form-group">
    {!! Form::label('label', 'Label:') !!}
    <p>{!! $optionFormItem->label !!}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{!! $optionFormItem->value !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $optionFormItem->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $optionFormItem->updated_at !!}</p>
</div>

resources/views/option_form_items/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection