routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('users', 'UserController');

Route::resource('userGroups', 'UserGroupController');

Route::resource('groupMembers', 'GroupMemberController');

Route::resource('avatars', 'AvatarController');

Route::resource('statusTemplateInspections', 'StatusTemplateInspectionController');

Route::resource('templateInspections', 'TemplateInspectionController');

Route::resource('statusInspectionForms', 'StatusInspectionFormController');

Route::resource('inspectionForms', 'InspectionFormController');

Route::resource('inspectionResponses', 'InspectionResponseController');

Route::resource('categoryInspectionForms', 'CategoryInspectionFormController');

Route::resource('statusCategoryForms', 'StatusCategoryFormController');

Route::resource('typeFormItems', 'TypeFormItemController');

Route::resource('inspectionFormItems', 'InspectionFormItemController');

Route::resource('priorityActionPlans', 'PriorityActionPlanController');

Route::resource('actionPlans', 'ActionPlanController');

Route::resource('observationFormItems', 'ObservationFormItemController');

Route::resource('optionFormItems', 'OptionFormItemController');

Route::resource('photographicEvidences', 'PhotographicEvidenceController');

Route::resource('typeRecurrences', 'TypeRecurrenceController');

Route::resource('customDateScheduleds', 'CustomDateScheduledController');

Route::resource('recurrenceScheduleds', 'RecurrenceScheduledController');

app/Models/ActionPlan.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class ActionPlan
 * @package App\Models
 * @version August 3, 2018, 11:36 am -05
 *
 * @property string description
 * @property string|\Carbon\Carbon date_time_end
 * @property integer assigned_user_id
 * @property integer priorities_id
 * @property string inspections_form_item_code
 * @property boolean closed
 * @property string hash_form
 */
class ActionPlan extends Model
{

    public $table = 'action_plans';
    


    public $fillable = [
        'description',
        'date_time_end',
        'assigned_user_id',
        'priorities_id',
        'inspections_form_item_code',
        'closed',
        'hash_form'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'description' => 'string',
        'assigned_user_id' => 'integer',
        'priorities_id' => 'integer',
        'inspections_form_item_code' => 'string',
        'closed' => 'boolean',
        'hash_form' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'description' => 'required',
        'date_time_end' => 'required',
        'assigned_user_id' => 'required|integer',
        'priorities_id' => 'required|integer',
        'inspections_form_item_code' => 'required',
        'closed' => 'required|boolean',
        'hash_form' => 'required'
    ];

    
}

app/Http/Controllers/ActionPlanController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ActionPlanDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateActionPlanRequest;
use App\Http\Requests\UpdateActionPlanRequest;
use App\Repositories\ActionPlanRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ActionPlanController extends AppBaseController
{
    /** @var  ActionPlanRepository */
    private $actionPlanRepository;

    public function __construct(ActionPlanRepository $actionPlanRepo)
    {
        $this->actionPlanRepository = $actionPlanRepo;
    }

    /**
     * Display a listing of the ActionPlan.
     *
     * @param ActionPlanDataTable $actionPlanDataTable
     * @return Response
     */
    public function index(ActionPlanDataTable $actionPlanDataTable)
    {
        return $actionPlanDataTable->render('action_plans.index');
    }

    /**
     * Show the form for creating a new ActionPlan.
     *
     * @return Response
     */
    public function create()
    {
        return view('action_plans.create');
    }

    /**
     * Store a newly created ActionPlan in storage.
     *
     * @param CreateActionPlanRequest $request
     *
     * @return Response
     */
    public function store(CreateActionPlanRequest $request)
    {
        $input = $request->all();

        $actionPlan = $this->actionPlanRepository->create($input);

        Flash::success('Action Plan saved successfully.');

        return redirect(route('actionPlans.index'));
    }

    /**
     * Display the specified ActionPlan.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $actionPlan = $this->actionPlanRepository->findWithoutFail($id);

        if (empty($actionPlan)) {
            Flash::error('Action Plan not found');

            return redirect(route('actionPlans.index'));
        }

        return view('action_plans.show')->with('actionPlan', $actionPlan);
    }

    /**
     * Show the form for editing the specified ActionPlan.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $actionPlan = $this->actionPlanRepository->findWithoutFail($id);

        if (empty($actionPlan)) {
            Flash::error('Action Plan not found');

            return redirect(route('actionPlans.index'));
        }

        return view('action_plans.edit')->with('actionPlan', $actionPlan);
    }

    /**
     * Update the specified ActionPlan in storage.
     *
     * @param  int              $id
     * @param UpdateActionPlanRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateActionPlanRequest $request)
    {
        $actionPlan = $this->actionPlanRepository->findWithoutFail($id);

        if (empty($actionPlan)) {
            Flash::error('Action Plan not found');

            return redirect(route('actionPlans.index'));
        }

        $actionPlan = $this->actionPlanRepository->update($request->all(), $id);

        Flash::success('Action Plan updated successfully.');

        return redirect(route('actionPlans.index'));
    }

    /**
     * Remove the specified ActionPlan from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $actionPlan = $this->actionPlanRepository->findWithoutFail($id);

        if (empty($actionPlan)) {
            Flash::error('Action Plan not found');

            return redirect(route('actionPlans.index'));
        }

        $this->actionPlanRepository->delete($id);

        Flash::success('Action Plan deleted successfully.');

        return redirect(route('actionPlans.index'));
    }
}

resources/views/action_plans/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Action Plan
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'actionPlans.store']) !!}

                        @include('action_plans.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/action_plans/datatables_actions.blade.php
{!! Form::open(['route' => ['actionPlans.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('actionPlans.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('actionPlans.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/action_plans/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Action Plan
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($actionPlan, ['route' => ['actionPlans.update', $actionPlan->id], 'method' => 'patch']) !!}

                        @include('action_plans.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/action_plans/fields.blade.php
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('actionPlans.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/action_plans/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Action Plans</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('actionPlans.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('action_plans.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $actionPlans])

        </div>
    </div>
@endsection

resources/views/action_plans/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Action Plan
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('action_plans.show_fields')
                    <a href="{!! route('actionPlans.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/action_plans/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $actionPlan->id !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $actionPlan->description !!}</p>
</div>

<!-- Date Time End Field -->
<div class="form-group">
    {!! Form::label('date_time_end', 'Date Time End:') !!}
    <p>{!! $actionPlan->date_time_end !!}</p>
</div>

<!-- Assigned User Id Field -->
<div class="form-group">
    {!! Form::label('assigned_user_id', 'Assigned User Id:') !!}
    <p>{!! $actionPlan->assigned_user_id !!}</p>
</div>

<!-- Priorities Id Field -->
<div class="form-group">
    {!! Form::label('priorities_id', 'Priorities Id:') !!}
    <p>{!! $actionPlan->priorities_id !!}</p>
</div>

<!-- Inspections Form Item Code Field -->
<div class="form-group">
    {!! Form::label('inspections_form_item_code', 'Inspections Form Item Code:') !!}
    <p>{!! $actionPlan->inspections_form_item_code !!}</p>
</div>

<!-- Closed Field -->
<div class="form-group">
    {!! Form::label('closed', 'Closed:') !!}
    <p>{!! $actionPlan->closed !!}</p>
</div>

<!-- Hash Form Field -->
<div class="form-group">
    {!! Form::label('hash_form', 'Hash Form:') !!}
    <p>{!! $actionPlan->hash_form !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $actionPlan->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $actionPlan->updated_at !!}</p>
</div>

resources/views/action_plans/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection