routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('users', 'UserController');

Route::resource('userGroups', 'UserGroupController');

Route::resource('groupMembers', 'GroupMemberController');

Route::resource('avatars', 'AvatarController');

Route::resource('statusTemplateInspections', 'StatusTemplateInspectionController');

Route::resource('templateInspections', 'TemplateInspectionController');

Route::resource('statusInspectionForms', 'StatusInspectionFormController');

Route::resource('inspectionForms', 'InspectionFormController');

Route::resource('inspectionResponses', 'InspectionResponseController');

Route::resource('categoryInspectionForms', 'CategoryInspectionFormController');

Route::resource('statusCategoryForms', 'StatusCategoryFormController');

Route::resource('typeFormItems', 'TypeFormItemController');

Route::resource('inspectionFormItems', 'InspectionFormItemController');

Route::resource('priorityActionPlans', 'PriorityActionPlanController');

Route::resource('actionPlans', 'ActionPlanController');

Route::resource('observationFormItems', 'ObservationFormItemController');

Route::resource('optionFormItems', 'OptionFormItemController');

Route::resource('photographicEvidences', 'PhotographicEvidenceController');

Route::resource('typeRecurrences', 'TypeRecurrenceController');

Route::resource('customDateScheduleds', 'CustomDateScheduledController');

Route::resource('recurrenceScheduleds', 'RecurrenceScheduledController');

app/Models/InspectionFormItem.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class InspectionFormItem
 * @package App\Models
 * @version August 3, 2018, 1:30 am -05
 *
 * @property string category_hash
 * @property string label
 * @property integer type_forms_items_id
 * @property string cod_item
 * @property integer required
 * @property integer published
 */
class InspectionFormItem extends Model
{

    public $table = 'inspection_form_items';
    


    public $fillable = [
        'category_hash',
        'label',
        'type_forms_items_id',
        'cod_item',
        'required',
        'published'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'category_hash' => 'string',
        'label' => 'string',
        'type_forms_items_id' => 'integer',
        'cod_item' => 'string',
        'required' => 'integer',
        'published' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'category_hash' => 'required',
        'label' => 'required',
        'type_forms_items_id' => 'required|integer',
        'cod_item' => 'required|max:10|string',
        'required' => 'integer|required',
        'published' => 'integer|required'
    ];

    
}

app/Http/Controllers/InspectionFormItemController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\InspectionFormItemDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateInspectionFormItemRequest;
use App\Http\Requests\UpdateInspectionFormItemRequest;
use App\Repositories\InspectionFormItemRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class InspectionFormItemController extends AppBaseController
{
    /** @var  InspectionFormItemRepository */
    private $inspectionFormItemRepository;

    public function __construct(InspectionFormItemRepository $inspectionFormItemRepo)
    {
        $this->inspectionFormItemRepository = $inspectionFormItemRepo;
    }

    /**
     * Display a listing of the InspectionFormItem.
     *
     * @param InspectionFormItemDataTable $inspectionFormItemDataTable
     * @return Response
     */
    public function index(InspectionFormItemDataTable $inspectionFormItemDataTable)
    {
        return $inspectionFormItemDataTable->render('inspection_form_items.index');
    }

    /**
     * Show the form for creating a new InspectionFormItem.
     *
     * @return Response
     */
    public function create()
    {
        return view('inspection_form_items.create');
    }

    /**
     * Store a newly created InspectionFormItem in storage.
     *
     * @param CreateInspectionFormItemRequest $request
     *
     * @return Response
     */
    public function store(CreateInspectionFormItemRequest $request)
    {
        $input = $request->all();

        $inspectionFormItem = $this->inspectionFormItemRepository->create($input);

        Flash::success('Inspection Form Item saved successfully.');

        return redirect(route('inspectionFormItems.index'));
    }

    /**
     * Display the specified InspectionFormItem.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $inspectionFormItem = $this->inspectionFormItemRepository->findWithoutFail($id);

        if (empty($inspectionFormItem)) {
            Flash::error('Inspection Form Item not found');

            return redirect(route('inspectionFormItems.index'));
        }

        return view('inspection_form_items.show')->with('inspectionFormItem', $inspectionFormItem);
    }

    /**
     * Show the form for editing the specified InspectionFormItem.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $inspectionFormItem = $this->inspectionFormItemRepository->findWithoutFail($id);

        if (empty($inspectionFormItem)) {
            Flash::error('Inspection Form Item not found');

            return redirect(route('inspectionFormItems.index'));
        }

        return view('inspection_form_items.edit')->with('inspectionFormItem', $inspectionFormItem);
    }

    /**
     * Update the specified InspectionFormItem in storage.
     *
     * @param  int              $id
     * @param UpdateInspectionFormItemRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateInspectionFormItemRequest $request)
    {
        $inspectionFormItem = $this->inspectionFormItemRepository->findWithoutFail($id);

        if (empty($inspectionFormItem)) {
            Flash::error('Inspection Form Item not found');

            return redirect(route('inspectionFormItems.index'));
        }

        $inspectionFormItem = $this->inspectionFormItemRepository->update($request->all(), $id);

        Flash::success('Inspection Form Item updated successfully.');

        return redirect(route('inspectionFormItems.index'));
    }

    /**
     * Remove the specified InspectionFormItem from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $inspectionFormItem = $this->inspectionFormItemRepository->findWithoutFail($id);

        if (empty($inspectionFormItem)) {
            Flash::error('Inspection Form Item not found');

            return redirect(route('inspectionFormItems.index'));
        }

        $this->inspectionFormItemRepository->delete($id);

        Flash::success('Inspection Form Item deleted successfully.');

        return redirect(route('inspectionFormItems.index'));
    }
}

resources/views/inspection_form_items/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inspection Form Item
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'inspectionFormItems.store']) !!}

                        @include('inspection_form_items.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/inspection_form_items/datatables_actions.blade.php
{!! Form::open(['route' => ['inspectionFormItems.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('inspectionFormItems.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('inspectionFormItems.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/inspection_form_items/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inspection Form Item
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($inspectionFormItem, ['route' => ['inspectionFormItems.update', $inspectionFormItem->id], 'method' => 'patch']) !!}

                        @include('inspection_form_items.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/inspection_form_items/fields.blade.php
<!-- Required Field -->
<div class="form-group col-sm-12">
    {!! Form::label('required', 'Required:') !!}
    <label class="radio-inline">
        {!! Form::radio('required', "1", null) !!} Si
    </label>

    <label class="radio-inline">
        {!! Form::radio('required', "0", null) !!} No
    </label>

</div>

<!-- Published Field -->
<div class="form-group col-sm-12">
    {!! Form::label('published', 'Published:') !!}
    <label class="radio-inline">
        {!! Form::radio('published', "1", null) !!} Si
    </label>

    <label class="radio-inline">
        {!! Form::radio('published', "0", null) !!} No
    </label>

</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('inspectionFormItems.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/inspection_form_items/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Inspection Form Items</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('inspectionFormItems.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('inspection_form_items.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $inspectionFormItems])

        </div>
    </div>
@endsection

resources/views/inspection_form_items/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Inspection Form Item
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('inspection_form_items.show_fields')
                    <a href="{!! route('inspectionFormItems.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/inspection_form_items/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $inspectionFormItem->id !!}</p>
</div>

<!-- Category Hash Field -->
<div class="form-group">
    {!! Form::label('category_hash', 'Category Hash:') !!}
    <p>{!! $inspectionFormItem->category_hash !!}</p>
</div>

<!-- Label Field -->
<div class="form-group">
    {!! Form::label('label', 'Label:') !!}
    <p>{!! $inspectionFormItem->label !!}</p>
</div>

<!-- Type Forms Items Id Field -->
<div class="form-group">
    {!! Form::label('type_forms_items_id', 'Type Forms Items Id:') !!}
    <p>{!! $inspectionFormItem->type_forms_items_id !!}</p>
</div>

<!-- Cod Item Field -->
<div class="form-group">
    {!! Form::label('cod_item', 'Cod Item:') !!}
    <p>{!! $inspectionFormItem->cod_item !!}</p>
</div>

<!-- Required Field -->
<div class="form-group">
    {!! Form::label('required', 'Required:') !!}
    <p>{!! $inspectionFormItem->required !!}</p>
</div>

<!-- Published Field -->
<div class="form-group">
    {!! Form::label('published', 'Published:') !!}
    <p>{!! $inspectionFormItem->published !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $inspectionFormItem->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $inspectionFormItem->updated_at !!}</p>
</div>

resources/views/inspection_form_items/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection