routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('users', 'UserController');

Route::resource('userGroups', 'UserGroupController');

Route::resource('groupMembers', 'GroupMemberController');

Route::resource('avatars', 'AvatarController');

Route::resource('statusTemplateInspections', 'StatusTemplateInspectionController');

Route::resource('templateInspections', 'TemplateInspectionController');

Route::resource('statusInspectionForms', 'StatusInspectionFormController');

Route::resource('inspectionForms', 'InspectionFormController');

Route::resource('inspectionResponses', 'InspectionResponseController');

Route::resource('categoryInspectionForms', 'CategoryInspectionFormController');

Route::resource('statusCategoryForms', 'StatusCategoryFormController');

Route::resource('typeFormItems', 'TypeFormItemController');

Route::resource('inspectionFormItems', 'InspectionFormItemController');

Route::resource('priorityActionPlans', 'PriorityActionPlanController');

Route::resource('actionPlans', 'ActionPlanController');

Route::resource('observationFormItems', 'ObservationFormItemController');

Route::resource('optionFormItems', 'OptionFormItemController');

Route::resource('photographicEvidences', 'PhotographicEvidenceController');

Route::resource('typeRecurrences', 'TypeRecurrenceController');

Route::resource('customDateScheduleds', 'CustomDateScheduledController');

Route::resource('recurrenceScheduleds', 'RecurrenceScheduledController');

app/Models/TypeFormItem.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class TypeFormItem
 * @package App\Models
 * @version August 2, 2018, 11:50 pm -05
 *
 * @property string title
 * @property string description
 * @property string type
 * @property string icon_name
 * @property string rules
 */
class TypeFormItem extends Model
{

    public $table = 'types_form_items';
    


    public $fillable = [
        'title',
        'description',
        'type',
        'icon_name',
        'rules'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'title' => 'string',
        'description' => 'string',
        'type' => 'string',
        'icon_name' => 'string',
        'rules' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'string|required|max:40|min:3',
        'type' => 'required|max:50|string',
        'icon_name' => 'string|required',
        'rules' => 'json'
    ];

    
}

app/Http/Controllers/TypeFormItemController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TypeFormItemDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateTypeFormItemRequest;
use App\Http\Requests\UpdateTypeFormItemRequest;
use App\Repositories\TypeFormItemRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class TypeFormItemController extends AppBaseController
{
    /** @var  TypeFormItemRepository */
    private $typeFormItemRepository;

    public function __construct(TypeFormItemRepository $typeFormItemRepo)
    {
        $this->typeFormItemRepository = $typeFormItemRepo;
    }

    /**
     * Display a listing of the TypeFormItem.
     *
     * @param TypeFormItemDataTable $typeFormItemDataTable
     * @return Response
     */
    public function index(TypeFormItemDataTable $typeFormItemDataTable)
    {
        return $typeFormItemDataTable->render('type_form_items.index');
    }

    /**
     * Show the form for creating a new TypeFormItem.
     *
     * @return Response
     */
    public function create()
    {
        return view('type_form_items.create');
    }

    /**
     * Store a newly created TypeFormItem in storage.
     *
     * @param CreateTypeFormItemRequest $request
     *
     * @return Response
     */
    public function store(CreateTypeFormItemRequest $request)
    {
        $input = $request->all();

        $typeFormItem = $this->typeFormItemRepository->create($input);

        Flash::success('Type Form Item saved successfully.');

        return redirect(route('typeFormItems.index'));
    }

    /**
     * Display the specified TypeFormItem.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $typeFormItem = $this->typeFormItemRepository->findWithoutFail($id);

        if (empty($typeFormItem)) {
            Flash::error('Type Form Item not found');

            return redirect(route('typeFormItems.index'));
        }

        return view('type_form_items.show')->with('typeFormItem', $typeFormItem);
    }

    /**
     * Show the form for editing the specified TypeFormItem.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $typeFormItem = $this->typeFormItemRepository->findWithoutFail($id);

        if (empty($typeFormItem)) {
            Flash::error('Type Form Item not found');

            return redirect(route('typeFormItems.index'));
        }

        return view('type_form_items.edit')->with('typeFormItem', $typeFormItem);
    }

    /**
     * Update the specified TypeFormItem in storage.
     *
     * @param  int              $id
     * @param UpdateTypeFormItemRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTypeFormItemRequest $request)
    {
        $typeFormItem = $this->typeFormItemRepository->findWithoutFail($id);

        if (empty($typeFormItem)) {
            Flash::error('Type Form Item not found');

            return redirect(route('typeFormItems.index'));
        }

        $typeFormItem = $this->typeFormItemRepository->update($request->all(), $id);

        Flash::success('Type Form Item updated successfully.');

        return redirect(route('typeFormItems.index'));
    }

    /**
     * Remove the specified TypeFormItem from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $typeFormItem = $this->typeFormItemRepository->findWithoutFail($id);

        if (empty($typeFormItem)) {
            Flash::error('Type Form Item not found');

            return redirect(route('typeFormItems.index'));
        }

        $this->typeFormItemRepository->delete($id);

        Flash::success('Type Form Item deleted successfully.');

        return redirect(route('typeFormItems.index'));
    }
}

resources/views/type_form_items/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Form Item
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'typeFormItems.store']) !!}

                        @include('type_form_items.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_form_items/datatables_actions.blade.php
{!! Form::open(['route' => ['typeFormItems.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('typeFormItems.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('typeFormItems.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/type_form_items/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Form Item
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($typeFormItem, ['route' => ['typeFormItems.update', $typeFormItem->id], 'method' => 'patch']) !!}

                        @include('type_form_items.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/type_form_items/fields.blade.php
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('typeFormItems.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/type_form_items/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Type Form Items</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('typeFormItems.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('type_form_items.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $typeFormItems])

        </div>
    </div>
@endsection

resources/views/type_form_items/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type Form Item
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('type_form_items.show_fields')
                    <a href="{!! route('typeFormItems.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/type_form_items/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $typeFormItem->id !!}</p>
</div>

<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    <p>{!! $typeFormItem->title !!}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{!! $typeFormItem->description !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $typeFormItem->type !!}</p>
</div>

<!-- Icon Name Field -->
<div class="form-group">
    {!! Form::label('icon_name', 'Icon Name:') !!}
    <p>{!! $typeFormItem->icon_name !!}</p>
</div>

<!-- Rules Field -->
<div class="form-group">
    {!! Form::label('rules', 'Rules:') !!}
    <p>{!! $typeFormItem->rules !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $typeFormItem->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $typeFormItem->updated_at !!}</p>
</div>

resources/views/type_form_items/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection